defmodule Revstack.Repo.Migrations.AddConsultingResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:leads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :email, :text, null: false
      add :company, :text
      add :message, :text, null: false
      add :preferred_contact_method, :text, null: false, default: "email"
      add :phone, :text
      add :status, :text, null: false, default: "new"
      add :source, :text, default: "website"
      add :honeypot, :text, default: ""

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:estimate_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :email, :text, null: false
      add :company, :text
      add :project_type, :text, null: false
      add :budget_range, :text
      add :timeline, :text
      add :summary, :text, null: false
      add :details, :text
      add :status, :text, null: false, default: "new"
      add :internal_size_tag, :text
      add :source, :text, default: "website"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:estimate_requests)

    drop table(:leads)
  end
end
